require "jekyll-leaflet/leaflet-map"
require "jekyll-leaflet/leaflet-items/leaflet-marker"
require "jekyll-leaflet/leaflet-items/leaflet-geojson"
require "jekyll-leaflet/leaflet-items/leaflet-cluster-marker"
require "jekyll-leaflet/filters/replace-hrefs"
